# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallon',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
